server:
  port: 9527
spring:
  application:
    name: springcloud-zuul


#Eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-zuul-9527  #修改Eureka的默认配置
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*" # 不能在使用这个路径访问  ignored： 忽略  ~忽略全部
  prefix: /xin #设置公共的前缀

info:
  app.name: xin
  company.name: xin.blog
