server:
  port: 7003
eureka:
  instance:
    hostname: localhost  #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向注册中心注册自己
    fetch-registry: false #fetch-registry如果为false，则表示自己为注册中心
    service-url:  #监控页面~
      # 集群，将其他Eureka的域名写进来（防止有一个注册中心崩了，剩下的还可以跑）
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

